lebguage: node_js
mode_js:
  - "12.16.3"
cache:
directories:
  - ./node_modules
before_install:
install:
  - npm install
before_script:
script:
  - npm run-script build
after_success:
after_failure:
after_script:
before_deploy:
deploy:
provider: pages
skip_cleanup: true
github_token: $GITHUB_TOKEN
local_dir: dist/starwars
on:
branch: master
