lebguage: node_js
mode_js:
  -  "12.16.3"
services:
  - docker
cache:
  directories:
    - ./node_modules
before_install:
    - docker ps -a
    - docker images
  install:
  # - npm install
  - docker build -t starwars .
  - docker run -d -p 8085:80 starwars:latest
before_script:
script:
  # - npm run-script test
  # - npm run-script build
after_success:
  - docker images
after_failure:
after_script:
before_deploy:
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/starwars
  on:
    branch: master

